In [4]:
import pandas as pd

El método pivot() se usa para reorganizar un DataFrame cambiando filas a columnas.

Usa valores únicos de una columna y los convierte en encabezados.

In [5]:
df = pd.DataFrame({
    "date": ["2023-01", "2023-01", "2023-02", "2023-02",],
    "city": ["London", "Paris", "London", "Paris"],
    "sales": [100, 120, 90, 110]
})

pivoted = df.pivot(index="date", columns="city", values="sales")

#df
pivoted

city     London  Paris
date
2023-01     100    120
2023-02      90    110

El método pivot_table() es parecido a pivot pero más flexible, permite adiciones aun habiendo valores repetidos.

Usa funciones como mean(), sum(), count(), etc.

In [6]:
df1 = pd.DataFrame({
    "city": ["London", "Paris", "London", "Paris"],
    "month": ["Jan", "Jan", "Feb", "March"],
    "sales": [100, 120, 90, 110]
})

pt = pd.pivot_table(df1, index="city", columns="month", values="sales", aggfunc="mean")

df1

     city  month  sales
0  London    Jan    100
1   Paris    Jan    120
2  London    Feb     90
3   Paris  March    110

In [7]:
pt

month    Feb    Jan  March
city
London  90.0  100.0    NaN
Paris    NaN  120.0  110.0

stack() -> mueve columnas al índice (filas)

unstack() -> mueve índices al nivel de columnas

In [8]:
data = {
    "A": [1, 2],
    "B": [3, 4]
}

df3 = pd.DataFrame(data, index=["rox1", "rox2"])

df3

      A  B
rox1  1  3
rox2  2  4

In [9]:
stack_table = df3.stack()
stack_table

rox1  A    1
      B    3
rox2  A    2
      B    4
dtype: int64

In [10]:
unstack_table = stack_table.unstack()
unstack_table

      A  B
rox1  1  3
rox2  2  4

Iterar en Pandas significa recorrer filas o columnas de un DataFrame.
los más comúnes son:

    -iterrows() -> itera fila por fila
    -itertuples() -> itera fila por fila, pero como tuplas
    -items() -> itera columna por columna

In [14]:
df4 = pd.DataFrame({
    "Name": ["Alice", "Bob", "Pato", "Leslie", "Maria", "Juan"],
    "Age": [25, 30, 22, 16, 45, 52]
})

#Iterar filas
for i, row in df4.iterrows():
    print(i, row["Name"], row["Age"])
    
print() #Espacio blanco

#Iterar columnas
for columns, values in df4.items():
    print(columns, list(values))

0 Alice 25
1 Bob 30
2 Pato 22
3 Leslie 16
4 Maria 45
5 Juan 52

Name ['Alice', 'Bob', 'Pato', 'Leslie', 'Maria', 'Juan']
Age [25, 30, 22, 16, 45, 52]

El método melt() agrupa las columnas en filas.

In [12]:
df5 = pd.DataFrame({
    "Date": ["2016-03-01", "2016-03-02", "2016-03-01", "2016-03-03", "2016-03-02", "2016-03-03"],
    "Type": ["a", "b", "c", "a", "a", "c"],
    "Values": [11.43, 13.03, 20.78, 99.90, 1.34, 20.78]
})

melt_table = pd.melt(df5, id_vars="Date", value_vars=["Type", "Values"], value_name="Observations")

melt_table

          Date variable Observations
0   2016-03-01     Type            a
1   2016-03-02     Type            b
2   2016-03-01     Type            c
3   2016-03-03     Type            a
4   2016-03-02     Type            a
5   2016-03-03     Type            c
6   2016-03-01   Values        11.43
7   2016-03-02   Values        13.03
8   2016-03-01   Values        20.78
9   2016-03-03   Values         99.9
10  2016-03-02   Values         1.34
11  2016-03-03   Values        20.78